"""empty message

Revision ID: 7d2f7b5531ee
Revises: cc7bb8f741c8
Create Date: 2022-09-28 15:48:40.361351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f7b5531ee'
down_revision = 'cc7bb8f741c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawling_product', sa.Column('category2', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawling_product', 'category2')
    # ### end Alembic commands ###
